In [1]:
import numpy as np

##### Importando librería Numpy


In [2]:
lista = list(range(1,11))
lista 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### transformando la lista a un array

In [3]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### corroborando el tipo de objeto

In [4]:
type(arreglo) #LOS ARREGLOS SON DE UN SOLO TIPO

numpy.ndarray

#### corroborando el tipo de datos del arreglo

In [5]:
arreglo.dtype #indica el tipo de dato del arreglo: float, int, str, booleano
# INT 32 = ENTERO DE 32 BITS, INDICA LA LONGITUD

dtype('int32')

#### definiendo el array de int32 a float32

In [6]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

#### transformando el array de int32 a float32

In [7]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [8]:
promedio = np.mean(arreglo)
promedio

5.5

In [9]:
mediana = np.median(arreglo)
mediana

5.5

In [10]:
desviacionestandar = np.std(arreglo)
desviacionestandar

2.8722813232690143

<h3 style = "color:blue"><b>ALGUNAS FUNCIONES DE NUMPY</b></h4>
NUMPY</b><h4>
<h1>TITULO</h1>
<h4 style = "color=aquamarine"><b> OBTENIENDO EL PROMEDIO DEL ARRAY</h3>